# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Slimefun Builder

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/**'
      - 'src/**'
      - 'pom.xml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ vars.JAVA_CI_VERSION }}
          java-package: jdk
          architecture: x64
          cache: maven

      - name: Build Slimefun
        run: mvn -s .mvn/settings.xml -B package --errors
        
      - uses: actions/upload-artifact@v3
        name: Upload Beta artifact
        with:
          name: Slimefun Beta Build
          path: target/Slimefun*.jar
          
      - uses: actions/download-artifact@v3
        name: Download Beta artifact
        with:
          name: Slimefun Beta Build
          path: downloaded_artifacts
          
      - name: List downloaded files
        run: ls -R downloaded_artifacts
        
      - name: Automatic Releases
        uses: marvinpinto/action-automatic-releases@v1.2.1
        if: github.ref_name == 'master'
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "Sicilia"
          prerelease: false
          title: "Slimefun 自动构建版本"
          files: |
            downloaded_artifacts/Slimefun*.jar
